
---

nginx:
    image: nginx
    volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/nginx/ssl/ipt-web.tacc.utexas.edu.bundle.crt:/etc/ssl/ipt-web/ipt-web.tacc.utexas.edu.bundle.crt
        - ./docker/nginx/ssl/ipt-web.tacc.utexas.edu.key:/etc/ssl/ipt-web/ipt-web.tacc.utexas.edu.key
    ports:
        - "4080:80"
        - "443:443"

django:
    image: jstubbs/ipt-web
    hostname: ipt-web.tacc.utexas.edu
    ports:
        - "8000:8000"
    extra_hosts:
        - "ipt-web.tacc.utexas.edu:172.17.0.1"
    environment:
        "IPT_INSTANCE": "dev"
        "AGAVE_CLIENT_KEY": "_6ofb8FswesLLarCOfXkVk1suUga"
        "AGAVE_CLIENT_SECRET":
        "AGAVE_BASE_URL": "https://api.tacc.utexas.edu"
        "AGAVE_SERVICE_TOKEN":
        "ACTOR_ID": "bde9c71e-9118-11e7-9e6c-0242ac110005-059"

