# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compile_command', models.CharField(max_length=50)),
                ('driver', models.CharField(max_length=75)),
                ('out_files', models.CharField(max_length=75)),
                ('compile_commandargs', models.CharField(max_length=50)),
                ('run_command', models.CharField(max_length=50)),
                ('job_queue', models.CharField(max_length=50)),
                ('est_run_time', models.DurationField()),
                ('alloc_num', models.CharField(max_length=50)),
                ('run_commargs', models.CharField(max_length=50)),
            ],
        ),
    ]
