# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('tag', models.CharField(max_length=50, null=True)),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Forum Entry',
                'verbose_name_plural': 'Forum Entries',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parentEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentParentEntry', to='messageBoard.Entry')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Forum Replies',
            },
        ),
    ]
